const { Nanny } = require("../models");

const nannyData = [
  {
    username: "natalie",
    password: "password",
    location: "chicago",
    years_experience: 2,
    education: "highschool",
    languages: "english",
    gender: "f",
  },
  {
    username: "ashley",
    password: "password1",
    location: "chicago",
    years_experience: 5,
    education: "bachelors",
    languages: "english, spanish",
    gender: "f",
  },
  {
    username: "jaden",
    password: "password2",
    location: "chicago",
    years_experience: 4,
    education: "masters",
    languages: "english",
    gender: "f",
  },
  {
    username: "john",
    password: "password3",
    location: "chicago",
    years_experience: 6,
    education: "masters",
    languages: "english, spanish",
    gender: "m",
  },
  {
    username: "mary",
    password: "password4",
    location: "chicago",
    years_experience: 3,
    education: "highschool",
    languages: "english",
    gender: "f",
  },
  {
    username: "anthony",
    password: "password5",
    location: "chicago",
    years_experience: 1,
    education: "highschool",
    languages: "english",
    gender: "m",
  },
  {
    username: "vincent",
    password: "password6",
    location: "chicago",
    years_experience: 4,
    education: "bachelors",
    languages: "english,spanish",
    gender: "m",
  },
  {
    username: "amanda",
    password: "password7",
    location: "chicago",
    years_experience: 10,
    education: "associates",
    languages: "english",
    gender: "f",
  },
  {
    username: "oliver",
    password: "password8",
    location: "chicago",
    years_experience: 8,
    education: "associates",
    languages: "english",
    gender: "m",
  },
  {
    username: "derek",
    password: "password9",
    location: "chicago",
    years_experience: 3,
    education: "associates",
    languages: "english",
    gender: "m",
  },
  {
    username: "kelsey",
    password: "password10",
    location: "chicago",
    years_experience: 4,
    education: "masters",
    languages: "english",
    gender: "f",
  },
  {
    username: "nathan",
    password: "password11",
    location: "chicago",
    years_experience: 6,
    education: "bachelors",
    languages: "english",
    gender: "m",
  },
];

const seedNanny = () => Nanny.bulkCreate(nannyData);

module.exports = seedNanny;
